services:
  db:
    image: postgres:16
    container_name: healthengine-pg
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: healthengine
    volumes:
      - healthengine_pgdata:/var/lib/postgresql/data

volumes:
  healthengine_pgdata:
